### ISSUE TITLE
Add TODO items from sent email

### ISSUE THREAD

**Issue by pjf** [pjf/exobrain#8]
In a nutshell, it'd be awesome to have exobrain scan my sent email and automatically generate TODO items.

Eg:

```
Hey client, I'm going to:

* Send (your company) a quote for (work). #todo
* Set up a new box for integration testing. #todo
* etc etc
```

Syntax to be properly decided. But I find myself sending clients a list of things I'll be doing for them, and then manually having to add those to my TODO manager.
- [ ] Figure out syntax
- [ ] Implement a sent message scanner that looks for said syntax
- [ ] Add a complimentary classifier for said scanner that adds to RTM.
##
